[package]
name = "f1t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.16", features = ["crossterm"] }
crossterm = "0.22"
f1 = { path = "../f1-rs" }